# Site settings
title: Lab notes
email: ivanustyuzh@gmail.com
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://ivust.com" # the base hostname & protocol for your site
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
